User context2
palantirnet/palantir-behat-extension pull request #36
Opened 2018-07-01 20:40 UTC by Etroid

## What, Why?
Updated the functions related to user and roles in Drupal 8.

```
Scenario: User exists and has roles
    When I examine the user "admin"
    Then the user should have the roles "Administrator"
    Then the user should not have the roles "Editor"
```

2018-07-03 18:33 UTC, damontgomery reviewed
This looks good to me. Thank @Etroid. I haven't had a chance to try it out, but I'll try to tackle that this week.

2018-07-03 18:33 UTC, damontgomery commented on src/Palantirnet/PalantirBehatExtension/Context/EntityDataContext.php
> +     * @throws \Exception if user does not have one ore more roles as defined in $roles
There is a typo in `one ore`.

2018-07-25 16:04 UTC, damontgomery requested changes
@Etroid, Sorry for the long delay on reviewing this. I tested this out and got errors when the tests failed since the `name()` method did not exist.

Could you try the suggested changes and let me know if that works for you?

2018-07-25 16:04 UTC, damontgomery commented on src/Palantirnet/PalantirBehatExtension/Context/EntityDataContext.php
> +                throw new \Exception(sprintf('User "%s" does not have role "%s".', $account->name(), $role->label()));
I get an error for this that the function `name()` doesn't exist. I was able to replace it with `$account->getAccountName()` and that worked.

2018-07-25 16:04 UTC, damontgomery commented on src/Palantirnet/PalantirBehatExtension/Context/EntityDataContext.php
> +                throw new \Exception(sprintf('User "%s" has role "%s".', $account->name(), $role->label()));
Same as above. I needed to replace `$account->name()` with `$account->getAccountName()`.

2018-07-25 21:13 UTC, Etroid commented
@damontgomery thanks for reviewing. You're absolutely right. Using `getAccountName` as found on `\Drupal\User\Entity\User` works like a charm 👍

2018-07-25 21:17 UTC, damontgomery approved these changes

2018-07-25 21:17 UTC, damontgomery commented
Thanks @Etroid!

2018-09-07 21:29 UTC, merged